services:
  sharelatex:
    restart: always
    # Server Pro users:
    # image: quay.io/sharelatex/sharelatex-pro
    image: sharelatex/sharelatex:with-texlive-full
    container_name: sharelatex
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    stop_grace_period: 60s
    volumes:
      - ./sharelatex_logs:/var/log/overleaf
      - ./sharelatex_data:/var/lib/overleaf
      ########################################################################
      ####  Server Pro: Uncomment the following line to mount the docker  ####
      ####             socket, required for Sibling Containers to work    ####
      ########################################################################
      # - /var/run/docker.sock:/var/run/docker.sock
    environment:

      OVERLEAF_APP_NAME: Overleaf (hosted by Maximilian Dorninger)

      OVERLEAF_MONGO_URL: mongodb://mongo/sharelatex

      # Same property, unfortunately with different names in
      # different locations
      OVERLEAF_REDIS_HOST: redis
      REDIS_HOST: redis

      ENABLED_LINKED_FILE_TYPES: 'project_file,project_output_file'

      # Enables Thumbnail generation using ImageMagick
      ENABLE_CONVERSIONS: 'true'

      # Disables email confirmation requirement
      EMAIL_CONFIRMATION_DISABLED: 'true'

      # temporary fix for LuaLaTex compiles
      # see https://github.com/overleaf/overleaf/issues/695
      TEXMFVAR: /var/lib/overleaf/tmp/texmf-var

      ## Set for SSL via nginx-proxy
      #VIRTUAL_HOST: 103.112.212.22

      OVERLEAF_SITE_URL: http://tex.maxid.me
      OVERLEAF_NAV_TITLE: Overleaf CE - Maximilian Dorninger
      # OVERLEAF_HEADER_IMAGE_URL: http://example.com/mylogo.png
      OVERLEAF_ADMIN_EMAIL: admin@maxid.me

      OVERLEAF_LEFT_FOOTER: '[{"text": "<a href=\"https://github.com/CookieDude24/LaTeX-Templates\">LaTeX-Vorlagen für Protokolle usw. hier</a>"} ]'
      OVERLEAF_RIGHT_FOOTER: '[{"text": "hosted by Maximilian Dorninger on Digital Ocean"} ]'

      OVERLEAF_EMAIL_FROM_ADDRESS: "tex@maxid.me"

      # OVERLEAF_EMAIL_AWS_SES_ACCESS_KEY_ID:
      # OVERLEAF_EMAIL_AWS_SES_SECRET_KEY:

      OVERLEAF_EMAIL_SMTP_HOST: "smtp.sendgrid.net"
      OVERLEAF_EMAIL_SMTP_PORT: 465
      OVERLEAF_EMAIL_SMTP_SECURE: true
      OVERLEAF_EMAIL_SMTP_USER: "apikey"
      OVERLEAF_EMAIL_SMTP_PASS: ${SMTP_API_KEY}
      # OVERLEAF_EMAIL_SMTP_TLS_REJECT_UNAUTH: true
      # OVERLEAF_EMAIL_SMTP_IGNORE_TLS: false
      OVERLEAF_EMAIL_SMTP_NAME: 'tex.maxid.me'
      OVERLEAF_EMAIL_SMTP_LOGGER: true
      OVERLEAF_CUSTOM_EMAIL_FOOTER: "This system is run by Maximlian Dorninger"

      # ENABLE_CRON_RESOURCE_DELETION: true

      ################
      ## Server Pro ##
      ################

      ## Sandboxed Compiles: https://github.com/overleaf/overleaf/wiki/Server-Pro:-Sandboxed-Compiles
      SANDBOXED_COMPILES: 'true'
      SANDBOXED_COMPILES_SIBLING_CONTAINERS: 'true'
      ### Bind-mount source for /var/lib/overleaf/data/compiles inside the container.
      SANDBOXED_COMPILES_HOST_DIR: '/home/user/sharelatex_data/data/compiles'

      ## Works with test LDAP server shown at bottom of docker compose
      # OVERLEAF_LDAP_URL: 'ldap://ldap:389'
      # OVERLEAF_LDAP_SEARCH_BASE: 'ou=people,dc=planetexpress,dc=com'
      # OVERLEAF_LDAP_SEARCH_FILTER: '(uid={{username}})'
      # OVERLEAF_LDAP_BIND_DN: 'cn=admin,dc=planetexpress,dc=com'
      # OVERLEAF_LDAP_BIND_CREDENTIALS: 'GoodNewsEveryone'
      # OVERLEAF_LDAP_EMAIL_ATT: 'mail'
      # OVERLEAF_LDAP_NAME_ATT: 'cn'
      # OVERLEAF_LDAP_LAST_NAME_ATT: 'sn'
      # OVERLEAF_LDAP_UPDATE_USER_DETAILS_ON_LOGIN: 'true'

      # OVERLEAF_TEMPLATES_USER_ID: "578773160210479700917ee5"
      # OVERLEAF_NEW_PROJECT_TEMPLATE_LINKS: '[ {"name":"All Templates","url":"/templates/all"}]'


      # OVERLEAF_PROXY_LEARN: "true"
    links:
      - mongo
      - redis
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tex-secured.rule=Host(`tex.maxid.me`)"
      - "traefik.http.routers.tex-secured.tls=true"
      - "traefik.http.routers.tex-secured.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.tex-secured.entrypoints=web-secure"

  mongo:
    restart: always
    image: mongo:5.0
    container_name: mongo
    command: '--replSet overleaf'
    volumes:
      - ./mongo_data:/data/db
      - ./mongodb-init-replica-set.js:/docker-entrypoint-initdb.d/mongodb-init-replica-set.js
    environment:
      MONGO_INITDB_DATABASE: sharelatex
    extra_hosts:
      # Required when using the automatic database setup for initializing the replica set.
      # This override is not needed when running the setup after starting up mongo.
      - mongo:127.0.0.1
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    expose:
      - 27017

  redis:
    restart: always
    image: redis:6.2
    container_name: redis
    expose:
      - 6379
    volumes:
      - ./redis_data:/data
